config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :clubs
  resources :club_types, only: %i[new create]

  get "welcome/index"
  get "welcome/about"
  get "about" => "welcome#about"
  get "faq" => "welcome#faq"
  get "contact" => "welcome#contact"

  root "welcome#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
# frozen_string_literal: true

class Club < ApplicationRecord
  has_one :club_type
end

app/models/club_type.rb
# frozen_string_literal: true

class ClubType < ApplicationRecord
  def self.find_by_name(name)
    ClubType.where(name: name)
  end

  def self.find_or_initialize_by(name)
    find_by(name: name) || ClubType.new
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save { self.role ||= :member }
  has_many :clubs

  before_save { self.email = email.downcase }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: %i[member admin]
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  def find_owner_by_club_id(club_id)
    user_id = Club.find(club_id).user_id
    User.find(user_id)
  end
end

app/controllers/club_types_controller.rb
# frozen_string_literal: true

class ClubTypesController < ApplicationController
  def new
    @club_type = ClubType.new
  end

  def create
    @club_type = ClubType.new
    @club_type.name = params[:club_type][:name]

    if @club_type.save
      flash[:notice] = "Club type was saved."
      redirect_to new_club_path
    else
      flash.now[:alert] = "There was an error saving the club type. Please try again."
      render :new
    end
  end
end

app/controllers/clubs_controller.rb
# frozen_string_literal: true

class ClubsController < ApplicationController
  attr_reader :owner
  # before_action :require_sign_in, only: [:delete, :destroy]

  before_action :authorize_user, only: %i[delete destroy edit]

  def index
    @clubs = if params[:club]
               Club.where("name LIKE ?", "%#{params[:club]}%")
             else
               Club.all
             end
  end

  def show
    @club = Club.find(params[:id])
    @owner = User.find(@club.user_id)
  end

  def new
    @club = Club.new
  end

  def create
    @club = Club.new
    @club.name = params[:club][:name]
    @club.address = params[:club][:address]
    @club.contact = params[:club][:contact]
    @club.email = current_user.email
    @club.user_id = current_user.id
    @club.active = params[:club][:active]
    @club.club_type_id = params[:club][:club_type_id]

    if @club.save
      flash[:notice] = "Club was saved."
      redirect_to @club
    else
      flash.now[:alert] = "There was an error saving the club. Please try again."
      render :new
    end
  end

  def edit
    @club = Club.find(params[:id])
  end

  def update
    @club = Club.find(params[:id])
    @club.name = params[:club][:name]
    @club.address = params[:club][:address]
    @club.contact = params[:club][:contact]
    @club.club_type_id = params[:club][:club_type_id]

    if @club.save
      flash[:notice] = "Club was updated."
      redirect_to @club
    else
      flash.now[:alert] = "There was an error saving the changes. Please try again."
      render :edit
    end
  end

  def destroy
    @club = Club.find(params[:id])

    if @club.destroy
      flash[:notice] = "\"#{@club.name}\" was deleted successfully."
      redirect_to clubs_path
    else
      flash.now[:alert] = "There was an error deleting the club."
      render :show
    end
  end

  private

  def authorize_user
    unless current_user.admin? || is_owner?
      flash[:alert] = "You must be an admin to do that."
      redirect_to club_path(params[:id])
    end
  end

   def is_owner?
    current_user == find_owner_by_club_id(params[:id])
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end

  def about; end

  def contact; end

  def faq; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/clubs_helper.rb
# frozen_string_literal: true

module ClubsHelper
end

app/views/club_types/new.html.haml
%h2
  Add a club type
= form_for @club_type do |f| 
  %div
    = f.label :name
    = f.text_field :name
  %div
    = f.submit "Save" 

app/views/clubs/_form.html.haml
= form_for @club do |f| 
	%div
		= f.label :name
		= f.text_field :name
	%div
		= f.label :address
		= f.text_area :address, placeholder: "Business address"
	%div	  
		= f.label :contact
		= f.text_field :contact, placeholder: "Name of principal contact"
	%div  
		= f.select :club_type_id, options_for_select(ClubType.all.pluck(:name, :id).uniq)
	%div
		= f.label :active
		= f.check_box :active  
	%div
		= f.submit "Save" 

app/views/clubs/edit.html.haml
%h2
  Edit Club form
= render partial: 'form'

app/views/clubs/index.html.haml
%h1
  Clubs
= form_tag(clubs_path, method: :get) do 
  Club
  = text_field_tag :club, params[:club]
  = submit_tag 'Search', name: nil
%ul
  - @clubs.each do |club|
    %li
      = link_to club.name, club_path(club.id)
      Club Type 
      = ClubType.find(club.club_type_id).name if club.club_type_id.present?
%p
  - if current_user.present?
    = link_to 'Create new club', new_club_path
  

app/views/clubs/new.html.haml
%h2
  New Club form
= render partial: 'form'
%p
  = link_to 'Add new club type', new_club_type_path

app/views/clubs/show.html.haml
%h1
	= @club.name
%div
	= "#{ClubType.find(@club.club_type_id).name} club" if @club.club_type_id.present?
	= "Club owner #{@owner.email}"
	- if current_user.present? && (current_user.admin? || current_user.id == @club.user_id)
		= link_to "Edit club", edit_club_path
		= link_to "Delete club", @club, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this club?' }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Summer Clubs
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
    = csp_meta_tag
  %body
    %div.container.header-login__status
      - if user_signed_in?
        Signed in as:
        %strong 
          = current_user.email
        = link_to 'Edit profile', edit_user_registration_path
        = link_to 'Sign out', destroy_user_session_path, method: :delete
      - else
        = link_to 'Sign up', new_user_registration_path
        = link_to 'Sign in', new_user_session_path       
      %ul.nav.nav-tabs
        %li= link_to "Home", root_path
        %li= link_to "Clubs", clubs_path 
        %li= link_to "About", about_path
        %li= link_to "FAQ", faq_path
        %li= link_to "Contact", contact_path
        
    - flash.each do |type, msg|
      %div{:class => "alert alert-#{type == :notice ? "success" : type}", "data-dismiss" => "alert"}
        %button.close &times;
        = msg if msg.is_a?(String)
    = yield

app/views/welcome/about.html.haml
%h1
  READ ALL ABOUT IT
= link_to "https://www.instagram.com/ciderm0nkey/", class: "btn btn-ins insta-icon" do
  = icon('fab', 'instagram')
   

app/views/welcome/contact.html.haml
%h1
  Contact Us

app/views/welcome/faq.html.haml
%h1
  FAQs

app/views/welcome/index.html.haml
%h1 
  homepage
%p
  "find me in app/views/welcome/index.html.haml"
  